// automatically generated by the FlatBuffers compiler, do not modify

package com.example.flatbuffertesting.product;

import com.google.flatbuffers.*;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ProductList extends Table {
  public static ProductList getRootAsProductList(ByteBuffer _bb) { return getRootAsProductList(_bb, new ProductList()); }
  public static ProductList getRootAsProductList(ByteBuffer _bb, ProductList obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ProductList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Product product(int j) { return product(new Product(), j); }
  public Product product(Product obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int productLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createProductList(FlatBufferBuilder builder,
      int productOffset) {
    builder.startObject(1);
    ProductList.addProduct(builder, productOffset);
    return ProductList.endProductList(builder);
  }

  public static void startProductList(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addProduct(FlatBufferBuilder builder, int productOffset) { builder.addOffset(0, productOffset, 0); }
  public static int createProductVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startProductVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endProductList(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishProductListBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

