// automatically generated by the FlatBuffers compiler, do not modify

package com.example.flatbuffertesting.product;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Product extends Table {
  public static Product getRootAsProduct(ByteBuffer _bb) {
    return getRootAsProduct(_bb, new Product());
  }

  public static Product getRootAsProduct(ByteBuffer _bb, Product obj) {
    _bb.order(ByteOrder.LITTLE_ENDIAN);
    return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
  }

  public void __init(int _i, ByteBuffer _bb) {
    bb_pos = _i;
    bb = _bb;
  }

  public Product __assign(int _i, ByteBuffer _bb) {
    __init(_i, _bb);
    return this;
  }

  public String amount() {
    int o = __offset(4);
    return o != 0 ? __string(o + bb_pos) : null;
  }

  public ByteBuffer amountAsByteBuffer() {
    return __vector_as_bytebuffer(4, 1);
  }

  public long id() {
    int o = __offset(6);
    return o != 0 ? bb.getLong(o + bb_pos) : 0L;
  }

  public String image() {
    int o = __offset(8);
    return o != 0 ? __string(o + bb_pos) : null;
  }

  public ByteBuffer imageAsByteBuffer() {
    return __vector_as_bytebuffer(8, 1);
  }

  public String link() {
    int o = __offset(10);
    return o != 0 ? __string(o + bb_pos) : null;
  }

  public ByteBuffer linkAsByteBuffer() {
    return __vector_as_bytebuffer(10, 1);
  }

  public String name() {
    int o = __offset(12);
    return o != 0 ? __string(o + bb_pos) : null;
  }

  public ByteBuffer nameAsByteBuffer() {
    return __vector_as_bytebuffer(12, 1);
  }

  public String source() {
    int o = __offset(14);
    return o != 0 ? __string(o + bb_pos) : null;
  }

  public ByteBuffer sourceAsByteBuffer() {
    return __vector_as_bytebuffer(14, 1);
  }

  public static int createProduct(FlatBufferBuilder builder,
      int amountOffset,
      long id,
      int imageOffset,
      int linkOffset,
      int nameOffset,
      int sourceOffset) {
    builder.startObject(6);
    Product.addId(builder, id);
    Product.addSource(builder, sourceOffset);
    Product.addName(builder, nameOffset);
    Product.addLink(builder, linkOffset);
    Product.addImage(builder, imageOffset);
    Product.addAmount(builder, amountOffset);
    return Product.endProduct(builder);
  }

  public static void startProduct(FlatBufferBuilder builder) {
    builder.startObject(6);
  }

  public static void addAmount(FlatBufferBuilder builder, int amountOffset) {
    builder.addOffset(0, amountOffset, 0);
  }

  public static void addId(FlatBufferBuilder builder, long id) {
    builder.addLong(1, id, 0L);
  }

  public static void addImage(FlatBufferBuilder builder, int imageOffset) {
    builder.addOffset(2, imageOffset, 0);
  }

  public static void addLink(FlatBufferBuilder builder, int linkOffset) {
    builder.addOffset(3, linkOffset, 0);
  }

  public static void addName(FlatBufferBuilder builder, int nameOffset) {
    builder.addOffset(4, nameOffset, 0);
  }

  public static void addSource(FlatBufferBuilder builder, int sourceOffset) {
    builder.addOffset(5, sourceOffset, 0);
  }

  public static int endProduct(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

